import { afterEach, beforeEach, describe, expect, expectTypeOf, it } from "vitest";
import { mkdtemp, rm, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  AREA_TYPES_FILENAME,
  PACKAGE_NAME,
  renderAugmentation,
  writeAreaTypes,
} from "./typegen.js";
import type { AreaId, AreaTag } from "./index.js";

describe("renderAugmentation", () => {
  it("emits a committed module augmentation, sorted + quoted", () => {
    const out = renderAugmentation(["tool-use", "refusal", "budget"]);
    expect(out).toBe(
      `// AUTO-GENERATED by agest — do not edit. Commit this file.\n` +
        `// Regenerate with \`agest typegen\` (also runs on \`agest run\` when missing).\n` +
        `import "@sebastiantuyu/agest";\n\n` +
        `declare module "@sebastiantuyu/agest" {\n` +
        `  interface AgestAreaRegistry {\n` +
        `    "budget": true;\n` +
        `    "refusal": true;\n` +
        `    "tool-use": true;\n` +
        `  }\n` +
        `}\n`,
    );
  });

  it("dedupes repeated ids", () => {
    const out = renderAugmentation(["a", "a", "b"]);
    expect(out.match(/"a": true;/g)).toHaveLength(1);
    expect(out).toContain(`"b": true;`);
  });

  it("targets the published package name", () => {
    expect(PACKAGE_NAME).toBe("@sebastiantuyu/agest");
    expect(renderAugmentation(["refusal"])).toContain(`declare module "${PACKAGE_NAME}"`);
  });
});

describe("writeAreaTypes", () => {
  let root: string;
  const filepath = () => join(root, AREA_TYPES_FILENAME);

  beforeEach(async () => {
    root = await mkdtemp(join(tmpdir(), "agest-typegen-"));
  });
  afterEach(async () => {
    await rm(root, { recursive: true, force: true });
  });

  const exists = async () =>
    readFile(filepath(), "utf-8").then(
      () => true,
      () => false,
    );

  it("skips an empty area set and writes nothing", async () => {
    expect(await writeAreaTypes(root, [])).toBe("skipped");
    expect(await exists()).toBe(false);
  });

  it("creates the file when missing", async () => {
    expect(await writeAreaTypes(root, ["refusal", "budget"])).toBe("created");
    expect(await readFile(filepath(), "utf-8")).toBe(renderAugmentation(["refusal", "budget"]));
  });

  it("is idempotent — unchanged when content matches", async () => {
    await writeAreaTypes(root, ["refusal"]);
    expect(await writeAreaTypes(root, ["refusal"])).toBe("unchanged");
  });

  it("leaves a stale file untouched without force (run mode)", async () => {
    await writeFile(filepath(), "// hand edited\n", "utf-8");
    expect(await writeAreaTypes(root, ["refusal"])).toBe("skipped");
    expect(await readFile(filepath(), "utf-8")).toBe("// hand edited\n");
  });

  it("overwrites a stale file with force (typegen mode)", async () => {
    await writeFile(filepath(), "// hand edited\n", "utf-8");
    expect(await writeAreaTypes(root, ["refusal"], { force: true })).toBe("updated");
    expect(await readFile(filepath(), "utf-8")).toBe(renderAugmentation(["refusal"]));
  });
});

/**
 * Type-level: in this (the library's own) compilation `AgestAreaRegistry` is
 * empty, so `AreaTag` resolves to its PERMISSIVE branch — catalog ids
 * autocomplete and any string is still accepted. The CLOSED branch (generated
 * file present) cannot be asserted here: a global augmentation would poison
 * every other test's compilation. It is proven instead by the NodeNext
 * consumer-sim in the verification step.
 */
describe("AreaTag (permissive branch — type-level)", () => {
  it("accepts catalog ids and arbitrary strings, and is always a string", () => {
    expectTypeOf<AreaId>().toExtend<AreaTag>();
    expectTypeOf<"a-made-up-domain-tag">().toExtend<AreaTag>();
    expectTypeOf<AreaTag>().toExtend<string>();
  });
});
