import { readFile, writeFile } from "node:fs/promises";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { loadConfig } from "./config.js";
import { resolveAreas } from "./areas.js";
import { c } from "./logger.js";

/**
 * `agest typegen` and its codegen core. We emit a committed `.d.ts` that
 * augments `AgestAreaRegistry` (see area-tags.ts) with the areas resolved from
 * `agest.config.ts` — the `next-env.d.ts` pattern: the test file never imports
 * the config, so a module augmentation is the only way to make the global
 * `scene().tags(...)` aware of a runtime-loaded config.
 *
 * `renderAugmentation` / `writeAreaTypes` are the pure-ish core (the only I/O is
 * a single file write); `main` is the CLI command and `generateAreaTypesOnRun`
 * is the generate-if-missing pass `agest run` invokes before spawning.
 */

/**
 * The published specifier consumers import from — and therefore the module the
 * generated file augments. Invariant, so hardcoded rather than read from a
 * manifest.
 */
export const PACKAGE_NAME = "@agest/core";

/**
 * Generated next to `agest.config.ts` (project root). Committed, not gitignored
 * — like `next-env.d.ts`, it's picked up by the consumer's default tsconfig
 * `include` so the augmentation is in scope for every test file.
 */
export const AREA_TYPES_FILENAME = "agest-env.d.ts";

const HEADER =
  `// AUTO-GENERATED by agest — do not edit. Commit this file.\n` +
  `// Regenerate with \`agest typegen\` (also runs on \`agest run\` when missing).\n`;

/**
 * Render the augmentation file body for a set of area ids. Pure and
 * deterministic: ids are deduped and sorted so the output is stable (no churn
 * from ordering) and snapshot-testable. The leading `import "<pkg>";` makes the
 * file a module, so `declare module` merges into the package's interface rather
 * than declaring a new ambient one. `JSON.stringify` quotes ids correctly
 * (`"tool-use"` needs quotes; a bare identifier would be a syntax error).
 */
export function renderAugmentation(areaIds: string[]): string {
  const sorted = [...new Set(areaIds)].sort();
  const members = sorted.map((id) => `    ${JSON.stringify(id)}: true;`).join("\n");
  return (
    HEADER +
    `import ${JSON.stringify(PACKAGE_NAME)};\n\n` +
    `declare module ${JSON.stringify(PACKAGE_NAME)} {\n` +
    `  interface AgestAreaRegistry {\n` +
    (members ? `${members}\n` : "") +
    `  }\n` +
    `}\n`
  );
}

export type WriteAreaTypesResult = "created" | "updated" | "unchanged" | "skipped";

/**
 * Write `agest-env.d.ts` into `cwd`. The state machine:
 *   - empty id set                         → "skipped" (nothing to constrain)
 *   - file missing                         → write, "created"
 *   - file present, content identical      → "unchanged" (idempotent, no churn)
 *   - file present, stale, `force` off     → "skipped" (don't clobber on a run)
 *   - file present, stale, `force` on      → write, "updated"
 *
 * `agest run` calls without `force` (generate-if-missing, never overwrite a
 * hand-edited/stale file mid-run). `agest typegen` calls with `force` (the
 * explicit, intentional refresh). `cwd` is a parameter for testability and
 * monorepo correctness — the caller passes `process.cwd()`.
 */
export async function writeAreaTypes(
  cwd: string,
  areaIds: string[],
  opts: { force?: boolean } = {},
): Promise<WriteAreaTypesResult> {
  if (areaIds.length === 0) return "skipped";

  const filepath = join(cwd, AREA_TYPES_FILENAME);
  const next = renderAugmentation(areaIds);

  let existing: string | null = null;
  try {
    existing = await readFile(filepath, "utf-8");
  } catch {
    /* missing — treat as create */
  }

  if (existing === null) {
    await writeFile(filepath, next, "utf-8");
    return "created";
  }
  if (existing === next) return "unchanged";
  if (!opts.force) return "skipped";
  await writeFile(filepath, next, "utf-8");
  return "updated";
}

/**
 * Resolve the opted-in area ids from the current config, or null when no
 * `areas` block is declared (so callers can no-op). Mirrors the loadConfig +
 * resolveAreas pairing that `agest coverage` and the runner use, so the
 * generated registry matches exactly what coverage measures.
 */
async function configuredAreaIds(): Promise<string[] | null> {
  const config = await loadConfig();
  if (!config.areas) return null;
  return [...resolveAreas(config.areas).optedIn.keys()];
}

/**
 * The generate-if-missing pass `agest run` invokes before spawning children
 * (parent-only — children share this cwd and would otherwise race to write the
 * same file). Best-effort: never overwrite a stale/edited file on a run (that's
 * `agest typegen`), and never throw — a bad config still surfaces precisely in
 * the child (context.ts).
 */
export async function generateAreaTypesOnRun(cwd: string): Promise<void> {
  try {
    const ids = await configuredAreaIds();
    if (!ids || ids.length === 0) return;
    const status = await writeAreaTypes(cwd, ids);
    if (status === "created") {
      console.log(
        c.dim(`  Generated ${AREA_TYPES_FILENAME} (commit it) — scene().tags() now checks your ${ids.length} configured areas.`),
      );
    } else if (status === "skipped") {
      console.log(c.dim(`  ${AREA_TYPES_FILENAME} is out of date — run \`agest typegen\` to refresh.`));
    }
  } catch {
    /* advisory only */
  }
}

/**
 * `agest typegen` — (re)write agest-env.d.ts from the configured areas so
 * scene().tags() type-checks against them. Unlike the generate-if-missing pass
 * inside `run`, this is the explicit, intentional refresh: it overwrites a
 * stale/hand-edited file. `--check` is the read-only CI guard: it writes
 * nothing and exits non-zero if the file is missing or out of date.
 */
export async function main(args: string[]): Promise<void> {
  const ids = await configuredAreaIds();
  if (ids === null) {
    console.log(`  No \`areas\` block in agest.config.ts — nothing to generate.`);
    return;
  }
  if (ids.length === 0) {
    console.log(`  Resolved area set is empty — nothing to generate.`);
    return;
  }

  if (args.includes("--check")) {
    const filepath = join(process.cwd(), AREA_TYPES_FILENAME);
    let existing: string | null = null;
    try {
      existing = readFileSync(filepath, "utf8");
    } catch {
      /* missing */
    }
    if (existing === renderAugmentation(ids)) {
      console.log(c.green(`  ${AREA_TYPES_FILENAME} is up to date.`));
      return;
    }
    console.error(
      c.red(`  ${AREA_TYPES_FILENAME} is ${existing === null ? "missing" : "out of date"}. Run \`agest typegen\`.`),
    );
    process.exit(1);
  }

  const status = await writeAreaTypes(process.cwd(), ids, { force: true });
  const msg =
    status === "unchanged"
      ? `${AREA_TYPES_FILENAME} already up to date (${ids.length} areas).`
      : `${status === "created" ? "Generated" : "Updated"} ${AREA_TYPES_FILENAME} (${ids.length} areas). Commit it.`;
  console.log(`  ${msg}`);
}
